macro create_field(ndim,name)
% scope.use :ppm_module_core
% scope.raw_var ({ result.to_sym => "class(ppm_t_field_), pointer :: #{result}" })
% scope.raw_var ({ :info => "integer :: info" })

allocate(ppm_t_field::<%= result %>,stat=info)
$or_fail_alloc("\"Allocating the <%= result %> field\"")

call <%= result %>%create(<%= ndim %>, info, name=<%= name %>)
$or_fail("\"Create field failed!\"")
end macro
