macro fail(test, message, type=ppm_err_alloc,info=info,exit_point=nil)
% scope.use :ppm_module_error
% scope.insert_exit_point unless exit_point
% scope.var "caller" => "character(len=#{scope.name.length}) :: caller = '#{scope.name}'"
if (<%= test %>) then
    call ppm_error(<%= type %>, caller, &
    <%= message %>, &
    100000, <%= info %>)
goto <%= exit_point ? exit_point : 9999 %>
end if
end macro
