macro simple(arg1, arg2)
% if not conf.mpi.nil? and conf.mpi
call MPI_Init()
% else
! mpi is off
% end
call ppm_init(info)
x = exp(<%= arg2 %>+2)
if (x .ge. 3.0_MK) then
  write(*,*) "Some Crap <%= arg1 %>"
end
end macro

macro fail(message, type=ppm_err_alloc,info=info,exit_point=9999)
call ppm_error(<%= type %>, &
  <%= message %>,&
  caller, 100000 , <%= info %>)
goto <%= exit_point %>
end macro

macro override()
old body
end macro

