macro simple(arg1, arg2)
% if not conf.mpi.nil? and conf.mpi
CALL MPI_Init()
% else
! mpi is off
% end
CALL ppm_init(info)
x = exp(<%= arg2 %>+2)
IF (x .GE. 3.0_MK) THEN
  WRITE(*,*) "Some Crap <%= arg1 %>"
ENDIF
end macro

macro fail(message, type=ppm_err_alloc,info=info,exit_point=9999)
CALL ppm_error(<%= type %>, &
  <%= message %>,&
  caller, 100000 , <%= info %>)
GOTO <%= exit_point %>
end macro

macro override()
old body
end macro

